@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InZpbmljaXVzLmdwZXJlaXJhMDNAZ21haWwuY29tIiwiaWQiOiI2OThiZDVkNDExMTY3NmYzODczNTRkYzkiLCJ1c2VybmFtZSI6InZpbmkiLCJ2YWxpZGF0aW9uX2hhc2giOiI0NDYzZDIwZTk2NDc5OWE2OTVmNjY1NjAwYzY3YTI5ZSJ9.UxMhoYSSAF_80SNsT4ijLSkrnUm2bkiJAzvs2Ez1Zd0


###
# @name postLists

post {{host}}/listas
Content-Type: application/json
apiKey: {{apiKey}}
Authorization: Bearer {{token}}

{
    "nome": "Lista de Teste"
}



###
# @name getLists
get {{host}}/listas
Content-Type: application/json
apiKey: {{apiKey}}
Authorization: Bearer {{token}}

###
# @name getListByID
get {{host}}/listas/1
Content-Type: application/json
apiKey: {{apiKey}}
Authorization: Bearer {{token}}

###
# @name closeList
put {{host}}/listas/1/finalizar
Content-Type: application/json
apiKey: {{apiKey}}
Authorization: Bearer {{token}}

{}